api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
    title: "API Tasks"
    description: "Sort your task by priority"
    version: "0.0.1"
    show_webby: false
    openapi:
        contact:
            name: Ticme
            url: https://www.github.com/molodoi
            email: hello@ticme.fr
